project:
  type: book
  execute-dir: file
  output-dir: _book


book:
  title: "Probability and Statistics for Data Science"
  subtitle: "getting to grips with randomness"
  author: "Peter Ralph"
  chapters:
    - index.qmd
    - introduction.qmd
    - count_data.qmd
    - method_of_moments.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
